In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

# We want to know if a book has a better rating when the number of pages is not high

In [2]:
df = pd.read_csv('df_for_analysis.csv')

For a fair comparaison we take only the books rated more than a hundred thousand time.

In [3]:
df = df[(df['numRatings']> 100000)]

In [4]:
df.to_csv('number_ratings_filtered.csv', index=False)

In [5]:
df['pages'].mean()

379.8978742245287

We will study a sample of the 25% top rated books.

In [7]:
top25 = df['rating'].quantile(q=0.75)
top25

4.21

In [8]:
top25 = df[(df['rating']> 4.21)]
top25

,bookId,title,author,genres,series,language,bookFormat,severalPublications,rating,pages,awards,numRatings,likedPercent,bbeScore,bbeVotes,price,5*,4*,3*,2*,1*
0,2767052-the-hunger-games,The Hunger Games,Suzanne Collins,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",Yes,English,Hardcover,No,4.33,374.000000,1,6376780,96.0,2993816,30516,5.090000,3444695.0,1921313.0,745221.0,171994.0,93557.0
1,2.Harry_Potter_and_the_Order_of_the_Phoenix,Harry Potter and the Order of the Phoenix,J.K. Rowling,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",Yes,English,Paperback,Yes,4.50,870.000000,1,2507623,98.0,2632233,26923,7.380000,1593642.0,637516.0,222366.0,39573.0,14526.0
2,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,Harper Lee,"['Classics', 'Fiction', 'Historical Fiction', ...",Yes,English,Paperback,Yes,4.28,324.000000,1,4501075,95.0,2269402,23328,9.657241,2363896.0,1333153.0,573280.0,149952.0,80794.0
3,1885.Pride_and_Prejudice,Pride and Prejudice,Jane Austen,"['Classics', 'Fiction', 'Romance', 'Historical...",No,English,Paperback,Yes,4.26,279.000000,0,2998241,94.0,1983116,20452,9.657241,1617567.0,816659.0,373311.0,113934.0,76770.0
5,19063.The_Book_Thief,The Book Thief,Markus Zusak,"['Historical Fiction', 'Fiction', 'Young Adult...",No,English,Hardcover,Yes,4.37,552.000000,1,1834276,96.0,1372809,14168,3.800000,1048230.0,524674.0,186297.0,48864.0,26211.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21275,9647295-the-way-of-kings,The Way of Kings,Brandon Sanderson,"['Fantasy', 'Fiction', 'Epic Fantasy', 'High F...",Yes,English,Other,Yes,4.63,316.321485,1,303454,98.0,100,1,8.570000,221838.0,60468.0,14141.0,4119.0,2888.0
27293,43925876-the-giver-of-stars,The Giver of Stars,Jojo Moyes,"['Historical Fiction', 'Fiction', 'Audiobook',...",No,English,Hardcover,Yes,4.28,388.000000,1,183231,97.0,97,1,16.100000,83114.0,74275.0,21046.0,3460.0,1336.0
32752,9188338-the-way-of-kings,The Way of Kings,Brandon Sanderson,"['Fantasy', 'Fiction', 'Epic Fantasy', 'High F...",Yes,English,Other,No,4.63,1137.000000,1,304529,98.0,93,1,22.470000,222482.0,60729.0,14210.0,4177.0,2931.0
37109,147732.Miss_Nelson_Is_Missing_,Miss Nelson Is Missing!,Harry Allard,"['Picture Books', 'Childrens', 'Fiction', 'Sch...",Yes,English,Paperback,Yes,4.29,32.000000,1,101275,95.0,87,1,2.070000,55279.0,26074.0,15117.0,3382.0,1423.0
38842,51791252-the-vanishing-half,The Vanishing Half,Brit Bennett,"['Fiction', 'Historical Fiction', 'Contemporar...",No,English,Hardcover,No,4.30,343.000000,0,131732,98.0,85,1,9.657241,59805.0,54926.0,14668.0,1803.0,530.0

In [10]:
from scipy.stats import ttest_1samp

# H0 = pages top rated books <= mean pages
# H1 = pages top rated books > mean pages

stat, pval = ttest_1samp(top25['pages'], 380)

print('stat is  ', stat)
print('pvalue for the two-tailed test is ', pval/2)

stat is   4.4442647682936265
pvalue for the two-tailed test is  5.7976914089176346e-06

The p value is very low but the stat is positive whereas the null hypothesis was 'less than' so we can reject the null hypothesis.

# A book is not better rated because it has a low number of pages.